language: julia

os:
  - linux

julia:
  - 1.0

notifications:
  email: false

after_success:

jobs:
  include:
    - stage: "Testing"
      julia: 1.0
      os: linux
      script:
        - julia --project=test/ -e 'using Pkg; Pkg.add("https://github.com/YoungFaithful/ClustForOpt.jl.git"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=test/ test/cep.jl
      name: "HTML"
      after_success:
services: docker
