language: julia

os:
  - linux

julia:
  - 1.0

notifications:
  email: false

after_success:

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));  Pkg.instantiate(); ] ; add https://github.com/YoungFaithful/ClustForOpt.jl#master'
        - julia --project=docs/ docs/make.jl
      after_success:
    - stage: "Testing"
      julia: 1.0
      os: linux
      script:
        - julia --project=test/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); ] ; add https://github.com/YoungFaithful/ClustForOpt.jl#master'
        - julia --project=test/ test/cep.jl
      after_success:
services: docker
